// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQRFAC9ridhAcGuk6pP1v9QFtt8nfgo7M',
    appId: '1:631834177621:web:0c5806cd6e3ca06f42a4dc',
    messagingSenderId: '631834177621',
    projectId: 'chat-app-5055b',
    authDomain: 'chat-app-5055b.firebaseapp.com',
    storageBucket: 'chat-app-5055b.appspot.com',
    measurementId: 'G-XKW81JMR4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgtBUJIll4PHBlSOXnE-6MHl_NXZGP4nU',
    appId: '1:631834177621:android:ae4f635e8d25c6ab42a4dc',
    messagingSenderId: '631834177621',
    projectId: 'chat-app-5055b',
    storageBucket: 'chat-app-5055b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDltYenBTvBUdqXSPcTuBFJy9bKPIIyHvE',
    appId: '1:631834177621:ios:94f34c279355701b42a4dc',
    messagingSenderId: '631834177621',
    projectId: 'chat-app-5055b',
    storageBucket: 'chat-app-5055b.appspot.com',
    iosBundleId: 'com.example.chatAppLast',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDltYenBTvBUdqXSPcTuBFJy9bKPIIyHvE',
    appId: '1:631834177621:ios:94f34c279355701b42a4dc',
    messagingSenderId: '631834177621',
    projectId: 'chat-app-5055b',
    storageBucket: 'chat-app-5055b.appspot.com',
    iosBundleId: 'com.example.chatAppLast',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQRFAC9ridhAcGuk6pP1v9QFtt8nfgo7M',
    appId: '1:631834177621:web:5c1c60aa8a21083742a4dc',
    messagingSenderId: '631834177621',
    projectId: 'chat-app-5055b',
    authDomain: 'chat-app-5055b.firebaseapp.com',
    storageBucket: 'chat-app-5055b.appspot.com',
    measurementId: 'G-YSG4HG5MKQ',
  );
}
